/* 콘텐츠 도구의 나머지 탭: 제작·장비(무기 주사위·가방·제작 옵션) · 이벤트(대화·선택지·초상화) · 기본 수치.
   editor.js 가 내놓은 ER.editor(작업본 C, 탭 등록, touch/status, 공용 위젯)를 쓴다. 설명 글은 data.js 의 gearText/effectText, events.js 의 lint/effectText 를 그대로 쓴다. */
(function (g) {
  'use strict';
  const ER = g.ER, D = ER.data, E = ER.editor, { C, TABS, HOOKS, GUIDES, $, el, esc, clone, optList, chipPicker, guideHtml, bindGuide, touch, status } = E;
  const { GEAR, CRAFT_OPTIONS, GEAR_SLOTS, GEAR_EFFECTS, MATERIALS, HEROES, REGIONS, RULES, PORTRAITS } = D, EV = ER.events;
  const ORIG = clone(D.BASE); // data.js 가 content 를 합치기 전에 떠 둔 원본
  const idOk = s => /^[a-z][a-z0-9_]*$/.test(s), num = (v, lo, hi) => Math.max(lo, Math.min(hi, Math.round(+v || 0)));
  const diceOk = s => { try { ER.dice.parse(s); return true; } catch (e) { return false; } };
  const diceInfo = s => { if (!diceOk(s)) return '형식: 1d8, 2d4+1, 1d6*2 처럼'; const b = ER.dice.bounds(s); return b.min + '~' + b.max + ' · 평균 ' + ((b.min + b.max) / 2).toFixed(1); };
  Object.assign(GUIDES, {
    craft: ['제작·장비 — 공방에서 만드는 무기·가방·장신구와 제작 옵션', ['왼쪽에서 장비를 고르거나 "새 장비"를 만듭니다. 칸은 무기(기본 공격 주사위를 바꿈)·가방(칸 수·묶음 크기)·장신구 셋입니다.', '"재료 비용"과 "공방 단계"가 제작 조건입니다. "효과"에서 수치를 더합니다(예: 가방 칸 +4, 치명타 +10%). 설명 글은 자동으로 만들어집니다.', '"붙일 수 있는 옵션"에 옵션을 넣고 옵션 칸 수를 정하면, 게임의 공방에서 그 장비에 옵션을 붙이고 뗄 수 있습니다. 옵션 자체는 아래 "제작 옵션" 목록에서 만듭니다.', '무기 주사위는 D&D식으로 적습니다: 1d8, 2d4+1. 옆에 범위와 평균이 바로 나옵니다. 치명타는 주사위를 한 번 더 굴립니다.']],
    events: ['이벤트 — 언제, 누가, 무슨 말을 하고, 무엇을 고르게 할지', ['"새 이벤트"를 만들고 트리거(언제 뜨는가)를 고릅니다. 지역·방 종류·플래그로 범위를 좁힐 수 있습니다.', '"대화"에 줄을 추가하고 말하는 이·초상화·좌우를 정합니다. {hero} 는 출격한 대원 이름으로 바뀝니다. 초상화는 아래 "초상화 관리"에서 그림 파일을 올려 추가합니다.', '"선택지"를 넣으면 마지막 줄에서 고르게 됩니다. 조건(금화·재료)과 효과(금화·재료·체력·시간·플래그…)를 붙이고, "답하는 말"과 "이어질 이벤트"로 흐름을 만듭니다.', '플래그를 켜 두고 다른 이벤트의 조건으로 쓰면 이야기가 이어집니다(예: 원정에서 도와준 사람이 귀환 뒤 찾아옴). "미리보기"로 대화창을 바로 확인하세요.']],
    tuning: ['기본 수치 — 게임 전체에 걸리는 숫자', ['바꾼 값만 content.js 에 덮어쓰기로 저장됩니다. "기본값"을 누르면 그 항목이 원래대로 돌아갑니다.', '가방 기본 칸 수, 재료 묶음 크기·판매가, 대원 체력·이동·맨손 주사위, 치명타·투지, 방 구성 규칙을 여기서 조절합니다.', '저장한 뒤 게임을 새로고침하면 반영됩니다. 진행 중인 원정에는 다음 원정부터 적용되는 값도 있습니다.']]
  });

  // 재료 비용 편집기: {mat: n}
  function costEditor(box, cost, onChange, withGold) {
    const draw = () => { const keys = Object.keys(cost); box.innerHTML = '<div class="chips">' + (keys.length ? keys.map(k => '<span class="chip">' + esc(k === 'gold' ? '금화' : MATERIALS[k]?.name || k) + ' <input type="number" min="1" max="99" value="' + cost[k] + '" data-k="' + k + '" style="width:48px;padding:0 4px"><button type="button" data-x="' + k + '" aria-label="빼기">×</button></span>').join('') : '<span class="dim small">없음</span>') + '</div><div class="row"><select>' + (withGold ? '<option value="gold">금화</option>' : '') + optList(MATERIALS) + '</select><button type="button" class="add">넣기</button></div>';
      box.querySelectorAll('[data-k]').forEach(i => { i.onchange = () => { cost[i.dataset.k] = num(i.value, 1, 99); onChange(); }; }); box.querySelectorAll('[data-x]').forEach(b => { b.onclick = () => { delete cost[b.dataset.x]; draw(); onChange(); }; }); box.querySelector('.add').onclick = () => { const k = box.querySelector('select').value; if (!cost[k]) cost[k] = 1; draw(); onChange(); }; };
    draw();
  }
  // 효과 편집기: {bonus:1, 'stack:ore':3}
  function effectEditor(box, fx, onChange) {
    const keys = () => Object.keys(GEAR_EFFECTS).concat(Object.keys(MATERIALS).map(m => 'stack:' + m)), label = k => (k.startsWith('stack:') ? (MATERIALS[k.slice(6)]?.name || k) + ' 묶음 +' : GEAR_EFFECTS[k] || k);
    const draw = () => { const mine = Object.keys(fx); box.innerHTML = (mine.length ? mine.map(k => '<div class="row small" style="margin-bottom:4px"><span style="flex:1">' + esc(label(k)) + '</span><input type="number" min="-20" max="99" value="' + fx[k] + '" data-k="' + esc(k) + '"><button type="button" class="danger" data-x="' + esc(k) + '">빼기</button></div>').join('') : '<div class="dim small" style="margin-bottom:4px">효과 없음</div>') + '<div class="row"><select>' + keys().filter(k => !(k in fx)).map(k => '<option value="' + esc(k) + '">' + esc(label(k)) + '</option>').join('') + '</select><button type="button" class="add">효과 추가</button></div>';
      box.querySelectorAll('[data-k]').forEach(i => { i.onchange = () => { fx[i.dataset.k] = num(i.value, -20, 99); onChange(); }; }); box.querySelectorAll('[data-x]').forEach(b => { b.onclick = () => { delete fx[b.dataset.x]; draw(); onChange(); }; }); box.querySelector('.add').onclick = () => { const k = box.querySelector('select').value; if (k) { fx[k] = 1; draw(); onChange(); } }; };
    draw();
  }

  // ───────── 제작·장비
  const CR = { id: 'longsword', mode: 'gear', opt: null, newOpen: false };
  const EFFECT_KEYS = k => GEAR_EFFECTS[k] || k.startsWith('stack:');
  function editGear(id, fn) { if (!C.gear[id]) C.gear[id] = clone(GEAR[id]); fn(C.gear[id]); const x = C.gear[id]; for (const k of Object.keys(x)) if (EFFECT_KEYS(k) && !x[k]) delete x[k]; if (!x.text) delete x.text; if (!x.heroes?.length) delete x.heroes; if (x.slot !== 'weapon') delete x.weapon; if (!x.options?.length) { delete x.options; delete x.optionSlots; } GEAR[id] = clone(x); touch(); }
  function editOpt(id, fn) { fn(C.craftOptions[id]); CRAFT_OPTIONS[id] = clone(C.craftOptions[id]); touch(); }
  function syncGear() { for (const k of Object.keys(GEAR)) if (!C.gear[k] && !ORIG.gear[k]) delete GEAR[k]; for (const k of new Set(Object.keys(ORIG.gear).concat(Object.keys(C.gear)))) GEAR[k] = clone(C.gear[k] || ORIG.gear[k]); for (const k of Object.keys(CRAFT_OPTIONS)) delete CRAFT_OPTIONS[k]; Object.assign(CRAFT_OPTIONS, clone(C.craftOptions)); }
  function gearUses(id) { const out = []; for (const q of Object.values(D.QUESTS)) if (q.reward?.gear === id) out.push('의뢰 보상'); return out; }
  function renderCraft() {
    const root = $('#tab-craft'); if (!GEAR[CR.id]) CR.id = Object.keys(GEAR)[0];
    root.innerHTML = guideHtml('craft') + '<div class="cols"><div><div class="list" id="crList"></div><div class="row" style="margin-top:6px"><button id="crNew" type="button">새 장비</button><button id="crNewOpt" type="button">새 옵션</button></div></div><div id="crMain"></div><div id="crSide"></div></div>'; bindGuide(root);
    const list = $('#crList');
    for (const [slot, label] of Object.entries(GEAR_SLOTS)) { list.append(el('div', 'grp', label)); for (const [id, x] of Object.entries(GEAR)) if ((x.slot || 'trinket') === slot) { const b = el('button', CR.mode === 'gear' && id === CR.id ? 'sel' : '', esc(x.name) + ' ' + (!ORIG.gear[id] ? '<span class="badge add">추가</span>' : C.gear[id] ? '<span class="badge mod">수정됨</span>' : '<span class="badge">기본</span>')); b.type = 'button'; b.onclick = () => { CR.mode = 'gear'; CR.id = id; CR.newOpen = false; renderCraft(); }; list.append(b); } }
    list.append(el('div', 'grp', '제작 옵션')); for (const [id, o] of Object.entries(C.craftOptions)) { const b = el('button', CR.mode === 'opt' && id === CR.opt ? 'sel' : '', esc(o.name) + ' <span class="badge">' + (o.slots || []).map(q => GEAR_SLOTS[q]).join('·') + '</span>'); b.type = 'button'; b.onclick = () => { CR.mode = 'opt'; CR.opt = id; CR.newOpen = false; renderCraft(); }; list.append(b); }
    $('#crNew').onclick = () => { CR.newOpen = 'gear'; renderCraft(); }; $('#crNewOpt').onclick = () => { CR.newOpen = 'opt'; renderCraft(); };
    const main = $('#crMain'), side = $('#crSide');
    if (CR.newOpen) { const isG = CR.newOpen === 'gear'; side.innerHTML = '';
      main.innerHTML = '<div class="panel"><h3>' + (isG ? '새 장비' : '새 제작 옵션') + '</h3><div class="form" style="max-width:520px"><label>이름</label><input id="cnName" type="text"><label>id</label><input id="cnId" type="text" placeholder="영문 소문자·숫자·_"><label>' + (isG ? '칸' : '붙는 칸') + '</label><select id="cnSlot">' + optList(GEAR_SLOTS, 'weapon', (k, v) => v) + '</select></div><div class="row" style="margin-top:8px"><button id="cnGo" class="primary" type="button">만들기</button><button id="cnCancel" type="button">취소</button></div></div>';
      $('#cnCancel').onclick = () => { CR.newOpen = false; renderCraft(); };
      $('#cnGo').onclick = () => { const id = $('#cnId').value.trim(), name = $('#cnName').value.trim(), slot = $('#cnSlot').value; if (!idOk(id) || !name || (isG ? GEAR[id] : C.craftOptions[id])) return status('이름을 적고, 겹치지 않는 id(영문 소문자·숫자·_)를 정하세요', 'bad');
        if (isG) { C.gear[id] = Object.assign({ name, slot, tier: 1, icon: slot === 'weapon' ? 'gear.sword' : slot === 'bag' ? 'gear.pack' : 'gear.coat', cost: { ore: 2 } }, slot === 'weapon' ? { weapon: { dice: '1d6', name: name + ' 공격' } } : slot === 'bag' ? { bag: 2 } : { hp: 2 }); GEAR[id] = clone(C.gear[id]); CR.mode = 'gear'; CR.id = id; }
        else { C.craftOptions[id] = { name, slots: [slot], cost: { ore: 1 }, effects: slot === 'bag' ? { bag: 1 } : slot === 'weapon' ? { bonus: 1 } : { hp: 2 } }; CRAFT_OPTIONS[id] = clone(C.craftOptions[id]); CR.mode = 'opt'; CR.opt = id; }
        CR.newOpen = false; touch(); renderCraft(); }; return; }
    if (CR.mode === 'opt' && C.craftOptions[CR.opt]) return renderOption(main, side, CR.opt);
    CR.mode = 'gear'; const id = CR.id, x = GEAR[id], w = x.weapon, icons = Object.keys(ER.ASSETS.assets).filter(a => a.startsWith('gear.')), fxOf = D.gearEffects(x), re = () => renderCraft();
    main.innerHTML = '<div class="panel"><h3>' + esc(x.name) + ' <span class="dim small">' + id + '</span></h3><div class="form"><label>이름</label><input id="gName" type="text" value="' + esc(x.name) + '"><label>칸</label><select id="gSlot">' + optList(GEAR_SLOTS, x.slot || 'trinket', (k, v) => v) + '</select><label>아이콘</label><select id="gIcon">' + icons.map(a => '<option' + (a === x.icon ? ' selected' : '') + '>' + a + '</option>').join('') + '</select><label>공방 단계</label><input id="gTier" type="number" min="1" max="3" value="' + Math.min(3, x.tier || 1) + '"' + (x.cost ? '' : ' disabled') + '><label>전용 대원</label><div class="row">' + Object.values(HEROES).map(h => '<label class="row"><input type="checkbox" data-hero="' + h.id + '"' + ((x.heroes || []).includes(h.id) ? ' checked' : '') + '>' + esc(h.name) + '</label>').join('') + '<span class="dim small">(비우면 누구나)</span></div><label>설명(선택)</label><textarea id="gText" placeholder="비우면 효과에서 자동으로 만든다">' + esc(x.text || '') + '</textarea></div></div>' +
      (w ? '<div class="panel"><h3>무기 — 기본 공격 주사위</h3><div class="form"><label>주사위</label><div class="row"><input id="wDice" type="text" value="' + esc(w.dice) + '" style="width:120px"><span id="wInfo" class="small">' + esc(diceInfo(w.dice)) + '</span></div><label>공격 이름</label><input id="wName" type="text" value="' + esc(w.name || '') + '"><label>사거리</label><div class="row"><input id="wRange" type="number" min="0" max="6" value="' + (w.range || 0) + '"><span class="dim small">0 = 대원의 기본 사거리</span></div></div><div class="dim small" style="margin-top:6px">맨손 주사위: ' + Object.values(HEROES).map(h => h.name + ' ' + h.attack.dice).join(' · ') + '. "정밀 타격"처럼 무기 피해를 쓰는 카드도 이 주사위를 굴립니다.</div></div>' : '') +
      '<div class="panel"><h3>재료 비용</h3>' + (x.cost ? '<div id="gCost"></div>' : '<div class="dim small">의뢰 보상 장비라 제작할 수 없다.</div>') + '</div><div class="panel"><h3>효과</h3><div id="gFx"></div></div><div class="panel"><h3>붙일 수 있는 옵션</h3><div class="row small" style="margin-bottom:6px">옵션 칸 <input id="gSlots" type="number" min="0" max="3" value="' + (x.options?.length ? x.optionSlots || 1 : 0) + '"></div><div id="gOpts"></div></div>';
    $('#gName').onchange = e => { editGear(id, q => { q.name = e.target.value.trim() || q.name; }); re(); }; $('#gSlot').onchange = e => { editGear(id, q => { q.slot = e.target.value; if (q.slot === 'weapon' && !q.weapon) q.weapon = { dice: '1d6', name: q.name + ' 공격' }; q.options = (q.options || []).filter(o => (C.craftOptions[o]?.slots || []).includes(q.slot)); }); re(); };
    $('#gIcon').onchange = e => editGear(id, q => { q.icon = e.target.value; }); $('#gTier').onchange = e => editGear(id, q => { q.tier = num(e.target.value, 1, 3); }); $('#gText').onchange = e => { editGear(id, q => { q.text = e.target.value.trim(); }); re(); };
    main.querySelectorAll('[data-hero]').forEach(c => { c.onchange = () => { editGear(id, q => { q.heroes = [...main.querySelectorAll('[data-hero]:checked')].map(i => i.dataset.hero); }); re(); }; });
    if (w) { $('#wDice').oninput = e => { $('#wInfo').textContent = diceInfo(e.target.value.trim()); }; $('#wDice').onchange = e => { const v = e.target.value.trim(); if (!diceOk(v)) return status('주사위식을 읽을 수 없습니다: ' + v, 'bad'); editGear(id, q => { q.weapon.dice = v; }); re(); }; $('#wName').onchange = e => editGear(id, q => { q.weapon.name = e.target.value.trim(); }); $('#wRange').onchange = e => editGear(id, q => { const v = num(e.target.value, 0, 6); if (v) q.weapon.range = v; else delete q.weapon.range; }); }
    if (x.cost) { const cost = clone(x.cost); costEditor($('#gCost'), cost, () => { editGear(id, q => { q.cost = clone(cost); }); renderCraftSide(side, id); }); }
    { const fx = clone(fxOf); effectEditor($('#gFx'), fx, () => { editGear(id, q => { for (const k of Object.keys(q)) if (EFFECT_KEYS(k)) delete q[k]; Object.assign(q, fx); }); renderCraftSide(side, id); }); }
    { const mine = (x.options || []).slice(), pool = Object.keys(C.craftOptions).filter(o => (C.craftOptions[o].slots || []).includes(x.slot || 'trinket')); if (pool.length) chipPicker($('#gOpts'), mine, pool, o => C.craftOptions[o]?.name || o, 9, () => { const uniq = [...new Set(mine)]; editGear(id, q => { q.options = uniq; q.optionSlots = Math.max(1, q.optionSlots || 1); }); re(); }); else $('#gOpts').innerHTML = '<div class="dim small">이 칸에 붙는 옵션이 아직 없다. 왼쪽 "새 옵션"으로 만드세요.</div>'; }
    $('#gSlots').onchange = e => { const v = num(e.target.value, 0, 3); editGear(id, q => { if (!v) q.options = []; else q.optionSlots = v; }); re(); };
    renderCraftSide(side, id);
  }
  function renderCraftSide(side, id) {
    const x = GEAR[id], uses = gearUses(id), opts = (x.options || []).slice(0, x.optionSlots || 1);
    side.innerHTML = '<div class="panel"><h3>게임에 보이는 모습</h3><div class="small"><b>[' + GEAR_SLOTS[x.slot || 'trinket'] + '] ' + esc(x.name) + '</b></div><div class="small" style="margin:4px 0">' + esc(D.gearText(id)) + '</div><div class="dim small">제작: ' + (x.cost ? esc(Object.entries(x.cost).map(([k, n]) => (MATERIALS[k]?.name || k) + ' ' + n).join(', ')) + ' · 공방 ' + (x.tier || 1) + '단계' : '의뢰 보상') + '</div>' + (opts.length ? '<div class="dim small" style="margin-top:6px">옵션을 모두 붙이면: ' + esc(D.gearText(id, opts)) + '</div>' : '') + '</div>' +
      (x.weapon ? '<div class="panel"><h3>주사위 비교</h3><table><thead><tr><th>무기</th><th>주사위</th><th>범위</th><th>평균</th></tr></thead><tbody>' + Object.values(HEROES).filter(h => !x.heroes?.length || x.heroes.includes(h.id)).map(h => '<tr><td>' + esc(h.name) + ' 맨손</td><td>' + h.attack.dice + '</td><td>' + diceInfo(h.attack.dice).split(' · ')[0] + '</td><td>' + diceInfo(h.attack.dice).split('평균 ')[1] + '</td></tr>').join('') + Object.entries(GEAR).filter(([, q]) => q.weapon && (q.heroes || []).join() === (x.heroes || []).join()).map(([k, q]) => '<tr' + (k === id ? ' style="color:var(--amber)"' : '') + '><td>' + esc(q.name) + '</td><td>' + esc(q.weapon.dice) + '</td><td>' + diceInfo(q.weapon.dice).split(' · ')[0] + '</td><td>' + (diceInfo(q.weapon.dice).split('평균 ')[1] || '') + '</td></tr>').join('') + '</tbody></table></div>' : '') +
      '<div class="panel"><h3>관리</h3><div class="row">' + (ORIG.gear[id] ? '<button id="gReset" type="button"' + (C.gear[id] ? '' : ' disabled') + '>기본값으로 되돌리기</button>' : '<button id="gDel" class="danger" type="button">이 장비 삭제</button>') + '</div>' + (uses.length ? '<div class="dim small" style="margin-top:6px">쓰이는 곳: ' + esc(uses.join(', ')) + '</div>' : '') + '<div class="dim small" style="margin-top:6px">이미 제작한 장비를 지우면 그 저장에서는 장비가 사라집니다.</div></div>';
    if ($('#gReset')) $('#gReset').onclick = () => { delete C.gear[id]; GEAR[id] = clone(ORIG.gear[id]); touch(); renderCraft(); };
    if ($('#gDel')) $('#gDel').onclick = () => { if (uses.length) return status('먼저 쓰이는 곳에서 빼세요', 'bad'); if (!confirm(x.name + ' 을(를) 지울까요?')) return; delete C.gear[id]; delete GEAR[id]; touch(); renderCraft(); };
  }
  function renderOption(main, side, id) {
    const o = C.craftOptions[id], usedBy = Object.entries(GEAR).filter(([, x]) => (x.options || []).includes(id)).map(([, x]) => x.name);
    main.innerHTML = '<div class="panel"><h3>제작 옵션: ' + esc(o.name) + ' <span class="dim small">' + id + '</span></h3><div class="form"><label>이름</label><input id="oName" type="text" value="' + esc(o.name) + '"><label>붙는 칸</label><div class="row">' + Object.entries(GEAR_SLOTS).map(([k, v]) => '<label class="row"><input type="checkbox" data-slot="' + k + '"' + ((o.slots || []).includes(k) ? ' checked' : '') + '>' + v + '</label>').join('') + '</div></div></div><div class="panel"><h3>재료 비용</h3><div id="oCost"></div></div><div class="panel"><h3>효과</h3><div id="oFx"></div></div>';
    side.innerHTML = '<div class="panel"><h3>게임에 보이는 모습</h3><div class="small"><b>' + esc(o.name) + '</b> — <span id="oPrev">' + esc(D.effectText(o.effects)) + '</span></div><div class="dim small" style="margin-top:6px">붙일 수 있는 장비: ' + esc(usedBy.join(', ') || '아직 없음 — 장비의 "붙일 수 있는 옵션"에 넣으세요') + '</div></div><div class="panel"><h3>관리</h3><button id="oDel" class="danger" type="button">이 옵션 삭제</button></div>';
    $('#oName').onchange = e => { editOpt(id, q => { q.name = e.target.value.trim() || q.name; }); renderCraft(); }; main.querySelectorAll('[data-slot]').forEach(c => { c.onchange = () => editOpt(id, q => { q.slots = [...main.querySelectorAll('[data-slot]:checked')].map(i => i.dataset.slot); }); });
    const cost = clone(o.cost || {}), fx = clone(o.effects || {}); costEditor($('#oCost'), cost, () => editOpt(id, q => { q.cost = clone(cost); })); effectEditor($('#oFx'), fx, () => { editOpt(id, q => { q.effects = clone(fx); }); $('#oPrev').textContent = D.effectText(fx); });
    $('#oDel').onclick = () => { if (usedBy.length) return status('먼저 장비에서 이 옵션을 빼세요: ' + usedBy.join(', '), 'bad'); if (!confirm(o.name + ' 을(를) 지울까요?')) return; delete C.craftOptions[id]; delete CRAFT_OPTIONS[id]; CR.mode = 'gear'; touch(); renderCraft(); };
  }

  // ───────── 이벤트
  const EVS = { id: null, newOpen: false };
  const syncEvents = () => { if (D.EVENTS !== C.events) { const copy = C.events.slice(); D.EVENTS.length = 0; D.EVENTS.push(...copy); } /* 처음에는 같은 배열이다: 비우면 작업본이 지워진다 */ for (const k of Object.keys(PORTRAITS)) if (!k.startsWith('actor.')) delete PORTRAITS[k]; Object.assign(PORTRAITS, C.portraits); };
  const evTouch = () => { syncEvents(); touch(); };
  const FILTER_UI = { region: ['지역', () => REGIONS], hero: ['대원', () => HEROES], roomType: ['방 종류', () => Object.fromEntries([...new Set(Object.values(REGIONS).flatMap(q => Object.keys(q.rooms_def)))].map(t => [t, { name: t }]))], room: ['수제 방', () => Object.fromEntries(C.rooms.map(r => [r.id, { name: r.name || r.id }]))], facility: ['시설', () => D.FACILITIES], outcome: ['결과', () => ({ extracted: { name: '귀환 성공' }, defeat: { name: '패배' } })] };
  function triggerText(t) { const m = EV.TRIGGERS[t?.type]; if (!m) return '트리거 없음'; const parts = [m.name]; for (const k of m.filters) if (t[k]) parts.push(FILTER_UI[k] ? (FILTER_UI[k][1]()[t[k]]?.name || t[k]) : k + ' ' + t[k]); if (t.flag) parts.push('플래그 ' + t.flag); if (t.notFlag) parts.push('플래그 ' + t.notFlag + ' 없음'); if (t.chance && t.chance < 100) parts.push(t.chance + '%'); if (t.repeat) parts.push('반복'); return parts.join(' · '); }
  const allFlags = () => [...new Set(C.events.flatMap(e => [e.trigger?.flag, e.trigger?.notFlag].concat((e.choices || []).flatMap(c => [c.require?.flag, c.require?.notFlag].concat((c.effects || []).map(f => f.flag))))).filter(Boolean))].sort();
  function renderEvents() {
    const root = $('#tab-events'); if (!C.events.find(e => e.id === EVS.id)) EVS.id = C.events[0]?.id || null; const ev = C.events.find(e => e.id === EVS.id);
    root.innerHTML = guideHtml('events') + '<div class="cols"><div><div class="list" id="evList"></div><div class="row" style="margin-top:6px"><button id="evNew" type="button">새 이벤트</button><button id="evDup" type="button"' + (ev ? '' : ' disabled') + '>복제</button><button id="evDel" class="danger" type="button"' + (ev ? '' : ' disabled') + '>삭제</button></div><div class="panel" style="margin-top:10px"><h3>초상화 관리</h3><div id="ptList"></div><div class="row" style="margin-top:6px"><input id="ptId" type="text" placeholder="id (예: scout)" style="width:100px"><input id="ptName" type="text" placeholder="이름" style="width:80px"></div><div class="row" style="margin-top:4px"><input id="ptFile" type="file" accept="image/png,image/jpeg,image/webp" style="max-width:190px"></div><div class="dim small" style="margin-top:4px">세로 3:4 그림이 가장 잘 맞습니다(1.5MB 이하). assets/portraits/ 에 저장됩니다.</div></div></div><div id="evMain"></div><div id="evSide"></div></div>'; bindGuide(root);
    const list = $('#evList'); if (!C.events.length) list.append(el('div', 'grp', '아직 이벤트가 없습니다.'));
    for (const [type, m] of Object.entries(EV.TRIGGERS)) { const mine = C.events.filter(e => e.trigger?.type === type); if (!mine.length) continue; list.append(el('div', 'grp', m.name)); for (const e of mine) { const bad = EV.lint(e).length, b = el('button', e.id === EVS.id ? 'sel' : '', esc(e.name || e.id) + (e.disabled ? ' <span class="badge">끔</span>' : '') + (bad ? ' <span class="badge" style="color:#ff9c95;border-color:#ff9c95">확인</span>' : '')); b.type = 'button'; b.onclick = () => { EVS.id = e.id; renderEvents(); }; list.append(b); } }
    $('#evNew').onclick = () => { let n = C.events.length + 1, id = 'event' + n; while (C.events.some(e => e.id === id)) id = 'event' + (++n); C.events.push({ id, name: '새 이벤트', trigger: { type: 'roomEnter' }, pages: [{ speaker: '', portrait: '', side: 'left', text: '' }], choices: [] }); EVS.id = id; evTouch(); renderEvents(); };
    $('#evDup').onclick = () => { const c = clone(ev); let n = 2; while (C.events.some(e => e.id === ev.id + '_' + n)) n++; c.id = ev.id + '_' + n; c.name = (ev.name || ev.id) + ' 사본'; C.events.push(c); EVS.id = c.id; evTouch(); renderEvents(); };
    $('#evDel').onclick = () => { const used = C.events.filter(e => (e.choices || []).some(c => c.next === ev.id)).map(e => e.name || e.id); if (used.length) return status('다른 이벤트가 이어 받고 있습니다: ' + used.join(', '), 'bad'); if (!confirm((ev.name || ev.id) + ' 을(를) 지울까요?')) return; C.events.splice(C.events.indexOf(ev), 1); EVS.id = null; evTouch(); renderEvents(); };
    renderPortraits();
    if (!ev) { $('#evMain').innerHTML = '<div class="panel"><div class="dim">왼쪽 "새 이벤트"로 시작하세요.</div></div>'; return; }
    const t = ev.trigger = ev.trigger || { type: 'roomEnter' }, meta = EV.TRIGGERS[t.type] || { filters: [] }, main = $('#evMain'), re = () => { evTouch(); renderEvents(); }, flags = allFlags(), flagList = '<datalist id="flagList">' + flags.map(f => '<option value="' + esc(f) + '">').join('') + '</datalist>';
    const ptOpts = cur => '<option value="">(없음)</option>' + Object.entries(PORTRAITS).map(([k, p]) => '<option value="' + esc(k) + '"' + (k === cur ? ' selected' : '') + '>' + esc(p.name || k) + '</option>').join('');
    main.innerHTML = flagList + '<div class="panel"><h3>' + esc(ev.name || ev.id) + '</h3><div class="form"><label>이름</label><input id="eName" type="text" value="' + esc(ev.name || '') + '"><label>id</label><input id="eId" type="text" value="' + esc(ev.id) + '"><label>언제</label><select id="eType">' + optList(EV.TRIGGERS, t.type, (k, v) => v.name + (v.where === 'run' ? ' (원정 중)' : ' (길드)')) + '</select>' +
      meta.filters.map(k => k === 'level' ? '<label>단계</label><input data-f="level" type="number" min="0" max="3" value="' + (t.level || 0) + '">' : '<label>' + FILTER_UI[k][0] + '</label><select data-f="' + k + '"><option value="">(모두)</option>' + optList(FILTER_UI[k][1](), t[k]) + '</select>').join('') +
      '<label>플래그 조건</label><div class="row"><input id="eFlag" type="text" list="flagList" placeholder="켜져 있어야 함" value="' + esc(t.flag || '') + '" style="width:150px"><input id="eNot" type="text" list="flagList" placeholder="꺼져 있어야 함" value="' + esc(t.notFlag || '') + '" style="width:150px"></div><label>확률 %</label><div class="row"><input id="eChance" type="number" min="1" max="100" value="' + (t.chance || 100) + '"><label class="row"><input id="eRepeat" type="checkbox"' + (t.repeat ? ' checked' : '') + '>볼 때마다 다시 뜸</label><label class="row"><input id="eOff" type="checkbox"' + (ev.disabled ? ' checked' : '') + '>끄기</label></div></div></div>' +
      '<div class="panel"><h3>대화</h3><div id="ePages"></div><button id="pAdd" type="button">+ 대사 추가</button></div><div class="panel"><h3>선택지 <span class="dim small">— 없으면 대화만 하고 닫힌다</span></h3><div id="eChoices"></div><button id="cAdd" type="button">+ 선택지 추가</button></div>';
    $('#eName').onchange = e => { ev.name = e.target.value.trim(); re(); }; $('#eId').onchange = e => { const v = e.target.value.trim(); if (!idOk(v) || C.events.some(q => q !== ev && q.id === v)) { e.target.value = ev.id; return status('id 는 겹치지 않는 영문 소문자·숫자·_', 'bad'); } for (const q of C.events) for (const c of q.choices || []) if (c.next === ev.id) c.next = v; ev.id = EVS.id = v; re(); };
    $('#eType').onchange = e => { const keep = { type: e.target.value }; for (const k of ['flag', 'notFlag', 'chance', 'repeat']) if (t[k]) keep[k] = t[k]; for (const k of EV.TRIGGERS[keep.type].filters) if (t[k]) keep[k] = t[k]; ev.trigger = keep; re(); };
    main.querySelectorAll('[data-f]').forEach(i => { i.onchange = () => { const v = i.dataset.f === 'level' ? num(i.value, 0, 3) : i.value; if (v) t[i.dataset.f] = v; else delete t[i.dataset.f]; re(); }; });
    const setOpt = (key, v) => { if (v) t[key] = v; else delete t[key]; }; $('#eFlag').onchange = e => { setOpt('flag', e.target.value.trim()); re(); }; $('#eNot').onchange = e => { setOpt('notFlag', e.target.value.trim()); re(); }; $('#eChance').onchange = e => { const v = num(e.target.value, 1, 100); setOpt('chance', v < 100 ? v : 0); re(); }; $('#eRepeat').onchange = e => { setOpt('repeat', e.target.checked); re(); }; $('#eOff').onchange = e => { if (e.target.checked) ev.disabled = true; else delete ev.disabled; re(); };
    const pages = $('#ePages'); ev.pages = ev.pages || [];
    ev.pages.forEach((p, i) => { const row = el('div', 'trait', '<div class="row small"><span class="dim">' + (i + 1) + '</span><input type="text" data-k="speaker" placeholder="말하는 이" value="' + esc(p.speaker || '') + '" style="width:110px"><select data-k="portrait">' + ptOpts(p.portrait) + '</select><select data-k="side"><option value="left"' + (p.side !== 'right' ? ' selected' : '') + '>왼쪽</option><option value="right"' + (p.side === 'right' ? ' selected' : '') + '>오른쪽</option></select><span style="flex:1"></span><button type="button" data-up>↑</button><button type="button" data-down>↓</button><button type="button" class="danger" data-del>빼기</button></div><textarea data-k="text" placeholder="대사" style="width:100%;margin-top:4px">' + esc(p.text || '') + '</textarea>');
      row.querySelectorAll('[data-k]').forEach(f => { f.onchange = () => { p[f.dataset.k] = f.value; if (f.dataset.k === 'portrait' && !p.speaker && PORTRAITS[f.value]) { p.speaker = PORTRAITS[f.value].name; } re(); }; });
      row.querySelector('[data-up]').onclick = () => { if (i) { ev.pages.splice(i - 1, 0, ev.pages.splice(i, 1)[0]); re(); } }; row.querySelector('[data-down]').onclick = () => { if (i < ev.pages.length - 1) { ev.pages.splice(i + 1, 0, ev.pages.splice(i, 1)[0]); re(); } }; row.querySelector('[data-del]').onclick = () => { ev.pages.splice(i, 1); re(); }; pages.append(row); });
    $('#pAdd').onclick = () => { const last = ev.pages[ev.pages.length - 1] || {}; ev.pages.push({ speaker: last.speaker || '', portrait: last.portrait || '', side: last.side || 'left', text: '' }); re(); };
    const where = meta.where || 'run', chBox = $('#eChoices'); ev.choices = ev.choices || [];
    ev.choices.forEach((c, i) => { c.effects = c.effects || []; const req = c.require || {}, reqMat = Object.keys(req.mat || {})[0] || '', box = el('div', 'trait');
      box.innerHTML = '<div class="row small"><span class="dim">' + (i + 1) + '</span><input type="text" data-c="label" placeholder="선택지 글" value="' + esc(c.label || '') + '" style="flex:1;min-width:160px"><button type="button" class="danger" data-del>빼기</button></div>' +
        '<div class="row small" style="margin-top:4px"><span class="dim" style="width:52px">조건</span>금화 <input type="number" data-r="gold" min="0" max="999" value="' + (req.gold || 0) + '">재료 <select data-r="mat"><option value="">(없음)</option>' + optList(MATERIALS, reqMat) + '</select><input type="number" data-r="matN" min="1" max="99" value="' + (req.mat?.[reqMat] || 1) + '"><input type="text" data-r="flag" list="flagList" placeholder="플래그 필요" value="' + esc(req.flag || '') + '" style="width:110px"></div>' +
        '<div class="small" style="margin-top:4px"><span class="dim">효과</span><div data-fx></div><div class="row" style="margin-top:2px"><select data-fxadd>' + Object.entries(EV.EFFECTS).filter(([, m]) => m.where === 'both' || m.where === where).map(([k, m]) => '<option value="' + k + '">' + m.name + '</option>').join('') + '</select><button type="button" data-fxbtn>효과 추가</button></div></div>' +
        '<div class="row small" style="margin-top:4px"><span class="dim" style="width:52px">답하는 말</span><input type="text" data-c="reply" placeholder="고른 뒤 상대가 하는 말(선택)" value="' + esc(c.reply || '') + '" style="flex:1"></div><div class="row small" style="margin-top:4px"><span class="dim" style="width:52px">이어짐</span><select data-c="next"><option value="">(끝)</option>' + C.events.filter(q => q !== ev).map(q => '<option value="' + q.id + '"' + (q.id === c.next ? ' selected' : '') + '>' + esc(q.name || q.id) + '</option>').join('') + '</select></div>';
      box.querySelectorAll('[data-c]').forEach(f => { f.onchange = () => { if (f.value) c[f.dataset.c] = f.value; else delete c[f.dataset.c]; re(); }; }); box.querySelector('[data-del]').onclick = () => { ev.choices.splice(i, 1); re(); };
      const saveReq = () => { const r = {}, gold = num(box.querySelector('[data-r=gold]').value, 0, 999), m = box.querySelector('[data-r=mat]').value, fl = box.querySelector('[data-r=flag]').value.trim(); if (gold) r.gold = gold; if (m) r.mat = { [m]: num(box.querySelector('[data-r=matN]').value, 1, 99) }; if (fl) r.flag = fl; if (Object.keys(r).length) c.require = r; else delete c.require; re(); }; box.querySelectorAll('[data-r]').forEach(f => { f.onchange = saveReq; });
      const fxBox = box.querySelector('[data-fx]'); c.effects.forEach((fx, k) => { const m = EV.EFFECTS[fx.type] || { name: fx.type, fields: [] }, row = el('div', 'row', '<span style="width:90px">' + esc(m.name) + '</span>' + (m.fields.includes('mat') ? '<select data-e="mat">' + optList(MATERIALS, fx.mat) + '</select>' : '') + (m.fields.includes('n') ? '<input type="number" data-e="n" min="-99" max="999" value="' + (fx.n || 0) + '"><span class="dim">(음수 = 잃음)</span>' : '') + (m.fields.includes('flag') ? '<input type="text" data-e="flag" list="flagList" placeholder="플래그 이름" value="' + esc(fx.flag || '') + '" style="width:130px">' : '') + '<button type="button" class="danger" data-x>빼기</button>'); row.style.marginTop = '2px';
        row.querySelectorAll('[data-e]').forEach(f => { f.onchange = () => { fx[f.dataset.e] = f.dataset.e === 'n' ? num(f.value, -99, 999) : f.value.trim(); re(); }; }); row.querySelector('[data-x]').onclick = () => { c.effects.splice(k, 1); re(); }; fxBox.append(row); });
      box.querySelector('[data-fxbtn]').onclick = () => { const type = box.querySelector('[data-fxadd]').value, m = EV.EFFECTS[type], fx = { type }; if (m.fields.includes('n')) fx.n = type === 'time' ? 2 : 5; if (m.fields.includes('mat')) fx.mat = 'wood'; if (m.fields.includes('flag')) fx.flag = ''; c.effects.push(fx); re(); }; chBox.append(box); });
    $('#cAdd').onclick = () => { ev.choices.push({ label: '', effects: [] }); re(); };
    const lint = EV.lint(ev), chain = C.events.filter(q => (q.choices || []).some(c => c.next === ev.id)).map(q => q.name || q.id);
    $('#evSide').innerHTML = '<div class="panel"><h3>요약</h3><div class="small">' + esc(triggerText(t)) + '</div><div class="dim small" style="margin-top:4px">대사 ' + ev.pages.length + '줄 · 선택지 ' + ev.choices.length + '개' + (chain.length ? ' · ' + esc(chain.join(', ')) + ' 에서 이어짐' : '') + '</div><div class="dim small" style="margin-top:4px">' + (t.repeat ? '조건이 맞을 때마다 뜹니다.' : '한 저장에서 한 번만 뜹니다.') + '</div></div><div class="panel"><h3>검사</h3><ul class="lint">' + (lint.length ? lint.map(m => '<li class="error">✖ ' + esc(m) + '</li>').join('') : '<li class="ok">✔ 문제 없음</li>') + '</ul></div><div class="panel"><h3>미리보기</h3><button id="evPrev" class="primary" type="button">대화창으로 보기</button><div class="dim small" style="margin-top:6px">선택지는 모두 고를 수 있는 상태로 보입니다. 효과는 적용되지 않습니다.</div></div>' + (flags.length ? '<div class="panel"><h3>쓰이는 플래그</h3><div class="small dim">' + esc(flags.join(', ')) + '</div></div>' : '');
    $('#evPrev').onclick = () => { syncEvents(); ER.dialog.open(ev, { vars: { hero: '아라' }, can: () => true, onChoose: k => { const c = ev.choices[k]; status(c ? '고름: ' + c.label + (EV.effectText(c.effects) ? ' → ' + EV.effectText(c.effects) : '') + (c.next ? ' → 이어짐: ' + c.next : '') : '대화 닫힘'); } }); };
  }
  function renderPortraits() {
    const box = $('#ptList'); box.innerHTML = ''; for (const [k, p] of Object.entries(PORTRAITS)) { const row = el('div', 'row small', '<span class="pthumb"></span><span style="flex:1">' + esc(p.name || k) + ' <span class="dim">' + esc(k) + '</span></span>' + (C.portraits[k] ? '<button type="button" class="danger">빼기</button>' : '<span class="badge">기본</span>')); row.style.marginBottom = '4px'; const th = row.querySelector('.pthumb'); th.style.cssText = 'width:30px;height:40px;border-radius:4px;border:1px solid var(--line);background:#0a0d0f center/cover no-repeat;display:inline-block;overflow:hidden'; if (p.src) th.style.backgroundImage = 'url("' + p.src + '")'; else { const a = ER.gfx.asset(p.asset); if (a) { const cv = document.createElement('canvas'); cv.width = 30; cv.height = 40; cv.style.cssText = 'width:100%;height:100%'; th.append(cv); const fr = (a.anims?.idle?.dirs?.down || a.anims?.idle?.frames || [])[0]; if (fr != null) ER.gfx.sprite(cv.getContext('2d'), p.asset, fr, 15, 55, 50, false, null); } }
      const del = row.querySelector('button'); if (del) del.onclick = () => { const used = C.events.filter(e => (e.pages || []).some(q => q.portrait === k)).map(e => e.name || e.id); if (used.length) return status('쓰는 이벤트가 있습니다: ' + used.join(', '), 'bad'); delete C.portraits[k]; evTouch(); renderEvents(); }; box.append(row); }
    $('#ptFile').onchange = e => { const f = e.target.files[0], id = $('#ptId').value.trim(), name = $('#ptName').value.trim(); if (!f) return; if (!idOk(id) || PORTRAITS[id]) { e.target.value = ''; return status('먼저 겹치지 않는 초상화 id(영문 소문자·숫자·_)를 적으세요', 'bad'); } if (f.size > 1.5e6) { e.target.value = ''; return status('그림이 1.5MB 를 넘습니다', 'bad'); } if (!E.canSave()) { e.target.value = ''; return status('그림 올리기는 로컬 서버(에디터 열기.bat)로 열었을 때만 됩니다', 'bad'); }
      const rd = new FileReader(); rd.onload = async () => { try { const r = await fetch('/__dev/portrait', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ id, dataUrl: rd.result }) }), j = await r.json(); if (!j.ok) return status('올리기 실패: ' + j.reason, 'bad'); C.portraits[id] = { name: name || id, src: j.src }; evTouch(); renderEvents(); status('초상화를 올렸습니다: ' + j.src + ' (저장을 눌러야 목록에 남습니다)', 'dirty'); } catch (err) { status('올리기 실패: ' + err.message, 'bad'); } }; rd.readAsDataURL(f); };
  }

  // ───────── 기본 수치
  const RULE_FIELDS = [['bagSlots', '가방 기본 칸', 1, 20], ['gearSlots', '장신구 칸', 0, 5], ['move', '기본 이동력(표시용)', 1, 8], ['deckSize', '덱 장수', 6, 20], ['startHand', '시작 손패', 1, 7], ['drawPerTurn', '턴당 드로우', 1, 4], ['handMax', '손패 상한', 3, 10], ['guardBlock', '기본 방어량', 0, 10], ['ambushBonus', '기습 피해 +', 0, 10],
    ['crit.base', '치명타 기본 %', 0, 100], ['crit.exposed', '빈틈 치명타 +%', 0, 100], ['gauge.max', '투지 최대', 1, 10], ['gauge.cost', '특수기 비용', 1, 10], ['level.guardRadius', '경비 반경', 1, 6], ['level.handmade', '수제 방 확률(0~1)', 0, 1, 0.05], ['level.hazardMax', '방당 경비 옆 위험 지형', 0, 6], ['time.gather', '채집 시간', 0, 5], ['time.door', '방 이동 시간', 0, 6], ['time.chest', '상자 시간', 0, 6], ['time.rest', '휴식 시간', 0, 10]];
  const getPath = (o, p) => p.split('.').reduce((q, k) => q?.[k], o), setPath = (o, p, v) => { const ks = p.split('.'); let q = o; for (const k of ks.slice(0, -1)) q = q[k] = q[k] || {}; q[ks[ks.length - 1]] = v; }, delPath = (o, p) => { const ks = p.split('.'); if (ks.length === 1) delete o[p]; else if (o[ks[0]]) { delete o[ks[0]][ks[1]]; if (!Object.keys(o[ks[0]]).length) delete o[ks[0]]; } };
  function cleanTuning() { const t = C.tuning; for (const k of ['rules', 'materials', 'heroes']) { for (const [id, v] of Object.entries(t[k] || {})) if (v && typeof v === 'object' && !Object.keys(v).length) delete t[k][id]; if (t[k] && !Object.keys(t[k]).length) delete t[k]; } }
  function syncTuning() { const t = C.tuning || {}; for (const [p] of RULE_FIELDS) setPath(RULES, p, getPath(t.rules || {}, p) ?? getPath(ORIG.rules, p)); for (const [k, m] of Object.entries(ORIG.materials)) Object.assign(MATERIALS[k], { stack: m.stack, value: m.value }, t.materials?.[k]); for (const [k, h] of Object.entries(ORIG.heroes)) { Object.assign(HEROES[k], { hp: h.hp, move: h.move }, t.heroes?.[k] && { hp: t.heroes[k].hp ?? h.hp, move: t.heroes[k].move ?? h.move }); HEROES[k].attack.dice = t.heroes?.[k]?.attack?.dice || h.attack.dice; } }
  function renderTuning() {
    const root = $('#tab-tuning'), t = C.tuning = C.tuning || {}, mod = v => (v ? ' <span class="badge mod">수정됨</span>' : '');
    const row = (label, input, changed, resetAttr) => '<tr><td>' + label + mod(changed) + '</td><td>' + input + '</td><td>' + (changed ? '<button type="button" ' + resetAttr + '>기본값</button>' : '') + '</td></tr>';
    root.innerHTML = guideHtml('tuning') + '<div class="cols" style="grid-template-columns:repeat(auto-fit,minmax(340px,1fr))"><div class="panel"><h3>규칙</h3><table><tbody>' + RULE_FIELDS.map(([p, label, lo, hi, step]) => { const cur = getPath(RULES, p), ch = getPath(t.rules || {}, p) !== undefined; return row(esc(label) + ' <span class="dim small">(기본 ' + getPath(ORIG.rules, p) + ')</span>', '<input type="number" data-rule="' + p + '" min="' + lo + '" max="' + hi + '" step="' + (step || 1) + '" value="' + cur + '">', ch, 'data-rreset="' + p + '"'); }).join('') + '</tbody></table></div>' +
      '<div class="panel"><h3>재료 — 묶음 크기와 판매가</h3><table><thead><tr><th>재료</th><th>묶음 · 판매가</th><th></th></tr></thead><tbody>' + Object.entries(MATERIALS).map(([k, m]) => row(esc(m.name) + ' <span class="dim small">(기본 ' + ORIG.materials[k].stack + ' · ' + ORIG.materials[k].value + ')</span>', '<input type="number" data-mat="' + k + '" data-f="stack" min="1" max="99" value="' + m.stack + '"> <input type="number" data-mat="' + k + '" data-f="value" min="0" max="99" value="' + m.value + '">', !!t.materials?.[k], 'data-mreset="' + k + '"')).join('') + '</tbody></table></div>' +
      '<div class="panel"><h3>대원</h3><table><thead><tr><th>대원</th><th>체력 · 이동 · 맨손 주사위</th><th></th></tr></thead><tbody>' + Object.values(HEROES).map(h => row(esc(h.name) + ' <span class="dim small">(기본 ' + ORIG.heroes[h.id].hp + ' · ' + ORIG.heroes[h.id].move + ' · ' + ORIG.heroes[h.id].attack.dice + ')</span>', '<input type="number" data-hero="' + h.id + '" data-f="hp" min="5" max="99" value="' + h.hp + '"> <input type="number" data-hero="' + h.id + '" data-f="move" min="1" max="8" value="' + h.move + '"> <input type="text" data-hero="' + h.id + '" data-f="dice" value="' + esc(h.attack.dice) + '" style="width:80px"> <span class="dim small">' + esc(diceInfo(h.attack.dice)) + '</span>', !!t.heroes?.[h.id], 'data-hreset="' + h.id + '"')).join('') + '</tbody></table><div class="dim small" style="margin-top:6px">가방 칸 = 기본 칸 + 보관 창고 단계 + 가방 장비. 묶음 = 재료 묶음 + 가방·주머니 효과.</div></div></div>'; bindGuide(root);
    const done = () => { cleanTuning(); syncTuning(); touch(); renderTuning(); };
    root.querySelectorAll('[data-rule]').forEach(i => { i.onchange = () => { const p = i.dataset.rule, v = Math.max(+i.min, Math.min(+i.max, +i.value || 0)); t.rules = t.rules || {}; if (v === getPath(ORIG.rules, p)) delPath(t.rules, p); else setPath(t.rules, p, v); done(); }; }); root.querySelectorAll('[data-rreset]').forEach(b => { b.onclick = () => { delPath(t.rules, b.dataset.rreset); done(); }; });
    root.querySelectorAll('[data-mat]').forEach(i => { i.onchange = () => { const k = i.dataset.mat, o = ORIG.materials[k], cur = { stack: num(root.querySelector('[data-mat=' + k + '][data-f=stack]').value, 1, 99), value: num(root.querySelector('[data-mat=' + k + '][data-f=value]').value, 0, 99) }; t.materials = t.materials || {}; t.materials[k] = {}; if (cur.stack !== o.stack) t.materials[k].stack = cur.stack; if (cur.value !== o.value) t.materials[k].value = cur.value; done(); }; }); root.querySelectorAll('[data-mreset]').forEach(b => { b.onclick = () => { delete t.materials[b.dataset.mreset]; done(); }; });
    root.querySelectorAll('[data-hero]').forEach(i => { i.onchange = () => { const k = i.dataset.hero, o = ORIG.heroes[k], q = f => root.querySelector('[data-hero=' + k + '][data-f=' + f + ']').value, dice = q('dice').trim(); if (!diceOk(dice)) { status('주사위식을 읽을 수 없습니다: ' + dice, 'bad'); return renderTuning(); } t.heroes = t.heroes || {}; const v = {}; if (num(q('hp'), 5, 99) !== o.hp) v.hp = num(q('hp'), 5, 99); if (num(q('move'), 1, 8) !== o.move) v.move = num(q('move'), 1, 8); if (dice !== o.attack.dice) v.attack = { dice }; t.heroes[k] = v; done(); }; }); root.querySelectorAll('[data-hreset]').forEach(b => { b.onclick = () => { delete t.heroes[b.dataset.hreset]; done(); }; });
  }

  Object.assign(TABS, { craft: renderCraft, events: renderEvents, tuning: renderTuning });
  HOOKS.restore.push(() => { syncGear(); syncEvents(); syncTuning(); });
  HOOKS.problems.push(() => { const out = []; for (const [k, x] of Object.entries(C.gear)) { if (x.weapon && !diceOk(x.weapon.dice)) out.push('장비 ' + k + ': 주사위식 오류'); for (const o of x.options || []) if (!C.craftOptions[o]) out.push('장비 ' + k + ': 없는 옵션 ' + o); for (const m of Object.keys(x.cost || {})) if (!MATERIALS[m]) out.push('장비 ' + k + ': 없는 재료 ' + m); } for (const e of C.events) { const l = EV.lint(e); if (l.length && !e.disabled) out.push('이벤트 ' + (e.name || e.id) + ': ' + l[0]); } return out; });
  syncEvents();
})(typeof globalThis !== 'undefined' ? globalThis : this);
